# Generated by Django 4.2 on 2024-02-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_site_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcoment',
            name='user_post',
            field=models.ForeignKey(blank=True, default=228, on_delete=django.db.models.deletion.CASCADE, to='game_site_api.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpic',
            name='user_post',
            field=models.ForeignKey(blank=True, default=288, on_delete=django.db.models.deletion.CASCADE, to='game_site_api.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcoment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
