# Generated by Django 4.2 on 2024-02-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_site_api', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcoment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
